language: node_js

os: linux

node_js:
  - "10"

cache:
  directories:
    - node_modules

# Set DISPLAY for Xvfb
env:
  - DISPLAY=:99.0

# 알림 설정
# see: https://docs.travis-ci.com/user/notifications#configuring-email-notifications
notifications:
  email:
    recipients:
      - molgga84@gmail.com
    on_success: never
    on_failure: always

# Job Lifecycle
# see: https://docs.travis-ci.com/user/job-lifecycle/#the-job-lifecycle

install:
  - npm run ci:bootstrap

services:
  - xvfb

script:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG

branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+(\-[0-9]+)?$/

# condition https://stackoverflow.com/questions/34591587/travis-conditional-on-branch-after-success
after_success:
#  - test $TRAVIS_BRANCH = "master" && \
#    test $TRAVIS_PULL_REQUEST = "false" && \
#    test $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+(\-[0-9]+)?$ && \
#    npm run ci:deploy-before
  - test $TRAVIS_BRANCH = "master" && \
    npm run ci:deploy-before

deploy:
  # 배포 설정 - github page
  - provider: pages
    edge: true
    skip_cleanup: true
    local_dir: docs
    github_token: $GITHUB_PAGES_TOKEN
    on:
      all_branches: true
      # condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+(\-[0-9]+)?$ # tag - v0.0.0 이 있는 경우만 publish

  # 배포 설정 - npm module
  - provider: npm
    edge: true
    skip_cleanup: true
    email: $NPM_PUBLISH_EMAIL
    api_key: $NPM_PUBLISH_TOKEN
    src: ./packages/lib
    access: public
    on:
      repo: molgga/jood-v-modal
      all_branches: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+(\-[0-9]+)?$ # tag - v0.0.0 이 있는 경우만 publish
