name: Build & Docs

on:
  # pull_request:
  #  branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn run bootstrap:install

      - name: Build
        run: yarn run package:build

      - name: Test
        run: yarn run package:test:unit

      - name: Docs:build
        run: yarn run docs:build

      - name: Docs:deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './document/docs/.vitepress/dist'
